### ISSUE TITLE
Not working with dirPagination(Michael Bromley)

### ISSUE THREAD

**Issue by logesh-kumar** [mattiash/angular-tablesort#18]
Hi, ts-repeat directive thorws error when used with dirPagination's dir-paginate directive. Throws this error. cannot read property 'match' of undefined(line no 167). Seems like empty objet is sent to regex match.

Thanks for the effort btw,

logesh

**Comment by mattiash** [comment]
I have never used dir-paginate and have no idea how it is supposed to work. Can you demonstrate the problem in a plunkr?

**Comment by abiaggi** [comment]
I don't know how to create a plunkr. but I installed https://github.com/michaelbromley/angularUtils/tree/master/src/directives/pagination and angular-tablesort.

Here is the code:

<dir-pagination-controls></dir-pagination-controls>
            <table class="table table-striped table-bordered" ts-wrapper>
                <thead>
					<tr>
						<th ts-criteria="title|lowercase">Title</th>
					</tr>
				</thead>
                <tbody>
                <tr dir-paginate="video in videos | itemsPerPage: 10" ts-repeat>
                    <td>
                        {{video.title}}
                    </td>
                </tr>
                </tbody>
            </table>

**Comment by mattiash** [comment]
I just released version 1.0.6. With that you can specify a "tablesort" in your ng-repeat expression. See the updated README and example.html for an example. With that, it ought to be possible to make it work.

**Comment by abiaggi** [comment]
How do I update to 1.0.6?

I ran bower update angular-tablesort but i get version 1.0.5

> bower update angular-tablesort
bower angular-tablesort#~1.0.5  cached git://github.com/mattiash/angular-tablesort.git#1.0.5
bower angular-tablesort#~1.0.5         validate 1.0.5 against git://github.com/mattiash/angular-tablesort.git#~1.0.5

**Comment by mattiash** [comment]
I forgot to push the v1.0.6 tag to github. Fixed now. Try bower update again.

/Mattias

**Comment by abiaggi** [comment]
I get a similar error with 1.0.6

>TypeError: Cannot read property 'match' of undefined
    at link (http://localhost:8080/my-project/bower_components/angular-tablesort/js/angular-tablesort.js:171:42)
    at nodeLinkFn (http://localhost:8080/my-project/bower_components/angular/angular.js:6704:13)
    at compositeLinkFn (http://localhost:8080/my-project/bower_components/angular/angular.js:6098:13)
    at compositeLinkFn (http://localhost:8080/my-project/bower_components/angular/angular.js:6101:13)
    at nodeLinkFn (http://localhost:8080/my-project/bower_components/angular/angular.js:6698:24)
    at compositeLinkFn (http://localhost:8080/my-project/bower_components/angular/angular.js:6098:13)
    at compositeLinkFn (http://localhost:8080/my-project/bower_components/angular/angular.js:6101:13)
    at nodeLinkFn (http://localhost:8080/my-project/bower_components/angular/angular.js:6698:24)
    at compositeLinkFn (http://localhost:8080/my-project/bower_components/angular/angular.js:6098:13)
    at compositeLinkFn (http://localhost:8080/my-project/bower_components/angular/angular.js:6101:13) <tr dir-paginate="video in videos | itemsPerPage: 10" ts-repeat="">

**Comment by abiaggi** [comment]
Please note that it's not using ng-repeat but the custom directive dir-paginate

**Comment by mattiash** [comment]
> Please note that it's not using ng-repeat but the custom directive dir-paginate

Then you have to make sure that angular-tablesort gets a chance to sort the entries before dir-paginate divides it into pages. I have never used dir-paginate, so I can't help you with that. My best guess would be to write

dir-paginate="video in videos | tablesort | itemsPerPage: 10"

but if that doesn't work then you have to roll up your sleeves and start looking at the code for angular-tablesort and dir-paginate.

**Comment by abiaggi** [comment]
I still have the same error. I might look into the code or try some other alternative.
Thanks

**Comment by sustbird** [comment]
I have forked and customized this library to work with dir-pagination. If anyone is interested, look here: https://github.com/sustbird/angular-tablesort

**Comment by dennisledford** [comment]
@sustbird I don't believe your change will work...i believe it will bypass the error and the table will load but the sorting functionality will not work.

**Comment by johnny0614** [comment]
@mattiash what i did is to instead of using ts-repeat direcitve, adding one more filter tablesortOrderBy at end of dir-paginate expression, like. 

dir-paginate="video in videos | itemsPerPage: 10 | tablesortOrderBy:sortFun"

seems working.
